### ISSUE TITLE
PixabayのCORS問題に関して

### ISSUE THREAD

**Issue by abekdwight** [orangedays00/gs_dev18_05#1]
お疲れ様です。課題フィードバックをしているチュータの阿部です。
課題フィードバックにも書きましたが、気になったのでここに書かせていただきます😁

PixabayのCORS問題に悩まれていたとのことですが、APIキーは間違っていないでしょうか？
確かに別ドメインからのアクセスを禁止されておりCORSでブロックされる場合もあると思います。
しかし今回は単にAPIキーが間違っているかのように思えます。
私の手元でAPIキーを発行し、貼り付けて利用してみたところちゃんと画像が表示されました。
<img src="https://user-images.githubusercontent.com/30901083/102455499-0f81f280-4083-11eb-8ef7-00c5a901991c.jpg" alt="テスト動作" width="400">

多分ですが、利用されているAPIキー(UUID的な方式のものだと思います)の先頭にある数字列は7桁ではなく、8桁ではないでしょうか？

APIキーが間違っていた結果、アクセスがブロックされ結果的にCORSに引っかかったという考え方もできそうです。
是非確認してみてください！！！

**Comment by orangedays00** [comment]
@TanisukeGoro 
ご確認ありがとうございます！

> PixabayのCORS問題に悩まれていたとのことですが、APIキーは間違っていないでしょうか？
> 確かに別ドメインからのアクセスを禁止されておりCORSでブロックされる場合もあると思います。

私の書き方がよくなく失礼しました。Pixabayからの画像表示自体はできておりました。

もともと実現したかったのが、
画像をクリックした場合に、下部の画像解析エリアにその画像を取り込み、そのまま、その画像を画像解析のAPIに投げることでした。
この場合に、CORS問題に当たった次第です。

APIで取得した、よそのサイトにある画像を、そのまま画像解析のAPIに投げようとしたところが問題だったのかなと考えております。

そのため今回は、一旦、ローカルに保存し、その画像をアップロードして、画像解析APIにかけ、その結果を表示するというところに妥協した次第です。

**Comment by abekdwight** [comment]
なるほど、Pixabayから取得した画像のURLをそのままCloud Visionに投げるとCORSに引っかかる感じなんですか？
画像データを取得する方法はいくつかあると思いますが、外部サーバーの画像をbase64したり弄ることはできないので難儀ですね。
画像が描画されている領域をcanvasでキャプチャして画像化=> cloud visionに投げるなどで対応すれば可能そうではありますが。。。

**Comment by orangedays00** [comment]
@TanisukeGoro 

> なるほど、Pixabayから取得した画像のURLをそのままCloud Visionに投げるとCORSに引っかかる感じなんですか？

おっしゃる通り、引っかかりました。

そして、ご返答いただいた、

> 画像が描画されている領域をcanvasでキャプチャして画像化=> cloud visionに投げるなどで対応すれば可能そうではありますが。。。

でできるだろうと思って、結構チャレンジしたのですが、うまくいかずでして。。。

**Comment by abekdwight** [comment]
そうでしたか。。となるとCORSの対策はちょっと厳しそうです😭

**Comment by orangedays00** [comment]
@TanisukeGoro 

ご確認ありがとうございました！
